 
/************************************************************************
 * FileName  DataTable\DataTableContextInfrastructure.IAg
 * FileDesc data/context
 * Author   System
 * CreateTime 2018-08-29 17:44:04

 * Copyright (c) Titan.Han  2017. All Rights Reserved. 
 * ***********************************************************************/

// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning
namespace Titan.Model.DataModel
{
    using System;
    using System.Linq;
    using Titan.Model;
    using System.Data.Entity;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations.Schema;

	#region POCO classes

    // SysCompany
    ///<summary>
    /// 服务器大区
    ///</summary>
    [Table("SysCompany")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public class SysCompany : IAggregateRoot
    {

        ///<summary>
        /// 机构Id
        ///</summary>
		[Description("机构Id")]
        public System.Guid SysCompanyId { get; set; } // SysCompanyId (Primary key)

        ///<summary>
        /// 机构名称
        ///</summary>
		[Description("机构名称")]
        public string SysCompanyName { get; set; } // SysCompanyName (length: 50)

        ///<summary>
        /// 机构父节点Id
        ///</summary>
		[Description("机构父节点Id")]
        public System.Guid? SysCompanyFatherId { get; set; } // SysCompanyFatherId

        ///<summary>
        /// 机构类型
        ///</summary>
		[Description("机构类型")]
        public int? CompanyType { get; set; } // CompanyType

        ///<summary>
        /// 机构状态
        ///</summary>
		[Description("机构状态")]
        public int? CompanyStatus { get; set; } // CompanyStatus

        ///<summary>
        /// 机构代码
        ///</summary>
		[Description("机构代码")]
        public string CompanyCode { get; set; } // CompanyCode (length: 50)

        ///<summary>
        /// 机构负责人
        ///</summary>
		[Description("机构负责人")]
        public string CompanyPicPerson { get; set; } // CompanyPicPerson (length: 20)

        ///<summary>
        /// 机构负责邮箱号
        ///</summary>
		[Description("机构负责邮箱号")]
        public string CompanyEmail { get; set; } // CompanyEmail (length: 50)

        ///<summary>
        /// 机构地址
        ///</summary>
		[Description("机构地址")]
        public string CompanyAddress { get; set; } // CompanyAddress (length: 200)

        ///<summary>
        /// 机构logo名字
        ///</summary>
		[Description("机构logo名字")]
        public string CompanyLogoName { get; set; } // CompanyLogoName (length: 100)

        ///<summary>
        /// 保留小数点位数
        ///</summary>
		[Description("保留小数点位数")]
        public string ReserveDecimalPoint { get; set; } // ReserveDecimalPoint (length: 20)

        ///<summary>
        /// 机构模板路径
        ///</summary>
		[Description("机构模板路径")]
        public string CompanyModel { get; set; } // CompanyModel (length: 200)

        ///<summary>
        /// 机构排序号
        ///</summary>
		[Description("机构排序号")]
        public int? CompanyOrderIndex { get; set; } // CompanyOrderIndex

        ///<summary>
        /// 机构首页类型
        ///</summary>
		[Description("机构首页类型")]
        public int? CompanyHomeType { get; set; } // CompanyHomeType

        ///<summary>
        /// 机构顶部图片
        ///</summary>
		[Description("机构顶部图片")]
        public string CompanyTopImgUrl { get; set; } // CompanyTopImgUrl (length: 200)

        ///<summary>
        /// 机构Logo图片
        ///</summary>
		[Description("机构Logo图片")]
        public string CompanyLogoImgUrl { get; set; } // CompanyLogoImgUrl (length: 200)

        ///<summary>
        /// 所属版本
        ///</summary>
		[Description("所属版本")]
        public string Version { get; set; } // Version (length: 40)

        ///<summary>
        /// 打印图标
        ///</summary>
		[Description("打印图标")]
        public string PrintImg { get; set; } // PrintImg (length: 200)

        ///<summary>
        /// 创建时间
        ///</summary>
		[Description("创建时间")]
        public System.DateTime? CreateTime { get; set; } // CreateTime

        ///<summary>
        /// 备注
        ///</summary>
		[Description("备注")]
        public string CompanyDesc { get; set; } // CompanyDesc (length: 500)

        ///<summary>
        /// 是否删除
        ///</summary>
		[Description("是否删除")]
        public bool? Isdelete { get; set; } // Isdelete

        ///<summary>
        /// 机构登录前缀
        ///</summary>
		[Description("机构登录前缀")]
        public string CompanyLoginCode { get; set; } // CompanyLoginCode (length: 20)

        ///<summary>
        /// 系统标题显示
        ///</summary>
		[Description("系统标题显示")]
        public string CompanyTitle { get; set; } // CompanyTitle (length: 50)

        // Reverse navigation

        /// <summary>
        /// Child SysDepts where [SysDept].[SysCompanyId] point to this entity (FK_SysDept_SYSCOMPAN_SysCompany)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SysDept> SysDepts { get; set; } // SysDept.FK_SysDept_SYSCOMPAN_SysCompany
        /// <summary>
        /// Child SysEmployees where [SysEmployee].[SysCompanyId] point to this entity (FK_SysEmployee_SYSEMPLOY_SysCompany)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SysEmployee> SysEmployees { get; set; } // SysEmployee.FK_SysEmployee_SYSEMPLOY_SysCompany
        /// <summary>
        /// Child SysQuartzTasks where [SysQuartzTask].[SysCompanyId] point to this entity (FK_SysQuartzTask_SYSCOMPAN_SysCompany)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SysQuartzTask> SysQuartzTasks { get; set; } // SysQuartzTask.FK_SysQuartzTask_SYSCOMPAN_SysCompany

        public SysCompany()
        {
            SysDepts = new System.Collections.Generic.List<SysDept>();
            SysEmployees = new System.Collections.Generic.List<SysEmployee>();
            SysQuartzTasks = new System.Collections.Generic.List<SysQuartzTask>();
        }
    }

    // SysDataBackM
    ///<summary>
    /// 数据库备份管理
    ///</summary>
    [Table("SysDataBackM")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public class SysDataBackM : IAggregateRoot
    {

        ///<summary>
        /// 数据库备份管理主键Id
        ///</summary>
		[Description("数据库备份管理主键Id")]
        public System.Guid DataBackMId { get; set; } // DataBackMId (Primary key)

        ///<summary>
        /// 用户主键Id
        ///</summary>
		[Description("用户主键Id")]
        public System.Guid? SysEmployeeId { get; set; } // SysEmployeeId

        ///<summary>
        /// 数据库备份文件名
        ///</summary>
		[Description("数据库备份文件名")]
        public string DataBackMFileName { get; set; } // DataBackMFileName (length: 100)

        ///<summary>
        /// 数据库备份开始时间
        ///</summary>
		[Description("数据库备份开始时间")]
        public System.DateTime? DataBackMStartTime { get; set; } // DataBackMStartTime

        ///<summary>
        /// 数据库备份结束时间
        ///</summary>
		[Description("数据库备份结束时间")]
        public System.DateTime? DataBackMEndTime { get; set; } // DataBackMEndTime

        ///<summary>
        /// 数据库文件大小
        ///</summary>
		[Description("数据库文件大小")]
        public string DataBackMFileSize { get; set; } // DataBackMFileSize (length: 40)

        ///<summary>
        /// 数据库文件路径
        ///</summary>
		[Description("数据库文件路径")]
        public string DataBackMFilePath { get; set; } // DataBackMFilePath (length: 500)
    }

    // SysDept
    ///<summary>
    /// 部门
    ///</summary>
    [Table("SysDept")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public class SysDept : IAggregateRoot
    {

        ///<summary>
        /// 部门主键Id
        ///</summary>
		[Description("部门主键Id")]
        public System.Guid SysDeptId { get; set; } // SysDeptId (Primary key)

        ///<summary>
        /// 机构Id
        ///</summary>
		[Description("机构Id")]
        public System.Guid? SysCompanyId { get; set; } // SysCompanyId

        ///<summary>
        /// 部门名称
        ///</summary>
		[Description("部门名称")]
        public string DeptName { get; set; } // DeptName (length: 20)

        ///<summary>
        /// 部门编号
        ///</summary>
		[Description("部门编号")]
        public string DeptCode { get; set; } // DeptCode (length: 20)

        ///<summary>
        /// 部门类型
        ///</summary>
		[Description("部门类型")]
        public int? DeptType { get; set; } // DeptType

        ///<summary>
        /// 部门状态
        ///</summary>
		[Description("部门状态")]
        public int? DeptStatus { get; set; } // DeptStatus

        ///<summary>
        /// 部门备注说明
        ///</summary>
		[Description("部门备注说明")]
        public string DeptDesc { get; set; } // DeptDesc (length: 200)

        ///<summary>
        /// 父级部门Id-上级主键Id
        ///</summary>
		[Description("父级部门Id-上级主键Id")]
        public System.Guid? DeptFatherId { get; set; } // DeptFatherId
        public bool? Isdelete { get; set; } // Isdelete

        // Reverse navigation

        /// <summary>
        /// Child SysPosts where [SysPost].[SysDeptId] point to this entity (FK_SysPost_SYSDEPT_S_SysDept)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SysPost> SysPosts { get; set; } // SysPost.FK_SysPost_SYSDEPT_S_SysDept
        // Foreign keys

        /// <summary>
        /// Parent SysCompany pointed by [SysDept].([SysCompanyId]) (FK_SysDept_SYSCOMPAN_SysCompany)
        /// </summary>
        public virtual SysCompany SysCompany { get; set; } // FK_SysDept_SYSCOMPAN_SysCompany

        public SysDept()
        {
            SysPosts = new System.Collections.Generic.List<SysPost>();
        }
    }

    // SysEmployee
    ///<summary>
    /// 系统员工
    ///</summary>
    [Table("SysEmployee")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public class SysEmployee : IAggregateRoot
    {

        ///<summary>
        /// 用户主键Id
        ///</summary>
		[Description("用户主键Id")]
        public System.Guid SysEmployeeId { get; set; } // SysEmployeeId (Primary key)

        ///<summary>
        /// 机构Id
        ///</summary>
		[Description("机构Id")]
        public System.Guid? SysCompanyId { get; set; } // SysCompanyId

        ///<summary>
        /// 岗位主键Id
        ///</summary>
		[Description("岗位主键Id")]
        public System.Guid? SysPostId { get; set; } // SysPostId

        ///<summary>
        /// 员工姓名
        ///</summary>
		[Description("员工姓名")]
        public string EmployeeName { get; set; } // EmployeeName (length: 30)

        ///<summary>
        /// 员工编号
        ///</summary>
		[Description("员工编号")]
        public string EmployeeCode { get; set; } // EmployeeCode (length: 20)

        ///<summary>
        /// 人员类型（0：护工；1：普通员工；2：管理员）
        ///</summary>
		[Description("人员类型（0：护工；1：普通员工；2：管理员）")]
        public int? EmployeeType { get; set; } // EmployeeType

        ///<summary>
        /// 员工状态
        ///</summary>
		[Description("员工状态")]
        public int? EmployeeStatus { get; set; } // EmployeeStatus

        ///<summary>
        /// 性别
        ///</summary>
		[Description("性别")]
        public int? Sex { get; set; } // Sex

        ///<summary>
        /// 出生日期
        ///</summary>
		[Description("出生日期")]
        public System.DateTime? Birthday { get; set; } // Birthday

        ///<summary>
        /// 手机号
        ///</summary>
		[Description("手机号")]
        public string Telphone { get; set; } // Telphone (length: 22)

        ///<summary>
        /// 帐号失效时间
        ///</summary>
		[Description("帐号失效时间")]
        public System.DateTime? NumberLoseTime { get; set; } // NumberLoseTime

        ///<summary>
        /// 员工身份证号
        ///</summary>
		[Description("员工身份证号")]
        public string IdNumber { get; set; } // IdNumber (length: 100)

        ///<summary>
        /// 员工账号
        ///</summary>
		[Description("员工账号")]
        public string EmployeeId { get; set; } // EmployeeId (length: 40)

        ///<summary>
        /// 员工密码
        ///</summary>
		[Description("员工密码")]
        public string EmployeePwd { get; set; } // EmployeePwd (length: 40)

        ///<summary>
        /// 员工头像
        ///</summary>
		[Description("员工头像")]
        public string EmployeePhotoUrl { get; set; } // EmployeePhotoUrl (length: 200)
        // Foreign keys

        /// <summary>
        /// Parent SysCompany pointed by [SysEmployee].([SysCompanyId]) (FK_SysEmployee_SYSEMPLOY_SysCompany)
        /// </summary>
        public virtual SysCompany SysCompany { get; set; } // FK_SysEmployee_SYSEMPLOY_SysCompany

        /// <summary>
        /// Parent SysPost pointed by [SysEmployee].([SysPostId]) (FK_SysEmployee_SYSEMPLOY_SysPost)
        /// </summary>
        public virtual SysPost SysPost { get; set; } // FK_SysEmployee_SYSEMPLOY_SysPost
    }

    // SysHandleLog
    ///<summary>
    /// 系统操作日志
    ///</summary>
    [Table("SysHandleLog")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public class SysHandleLog : IAggregateRoot
    {

        ///<summary>
        /// 操作记录主键Id
        ///</summary>
		[Description("操作记录主键Id")]
        public System.Guid SysHandleLogId { get; set; } // SysHandleLogId (Primary key)

        ///<summary>
        /// 用户主键Id
        ///</summary>
		[Description("用户主键Id")]
        public System.Guid? SysEmployeeId { get; set; } // SysEmployeeId

        ///<summary>
        /// 系统模块主键Id
        ///</summary>
		[Description("系统模块主键Id")]
        public System.Guid? SysTitleId { get; set; } // SysTitleId

        ///<summary>
        /// 操作时间
        ///</summary>
		[Description("操作时间")]
        public System.DateTime? HandleTime { get; set; } // HandleTime

        ///<summary>
        /// 操作动作
        ///</summary>
		[Description("操作动作")]
        public int? HandleAction { get; set; } // HandleAction

        ///<summary>
        /// 业务Id
        ///</summary>
		[Description("业务Id")]
        public System.Guid? HandleDataId { get; set; } // HandleDataId

        ///<summary>
        /// IP地址
        ///</summary>
		[Description("IP地址")]
        public string HandleLogIP { get; set; } // HandleLogIP (length: 100)

        ///<summary>
        /// 日志所属机构Id
        ///</summary>
		[Description("日志所属机构Id")]
        public System.Guid? HandleActionCID { get; set; } // HandleActionCID

        ///<summary>
        /// 备注
        ///</summary>
		[Description("备注")]
        public string HandleLogDesc { get; set; } // HandleLogDesc (length: 500)

        ///<summary>
        /// 是否删除
        ///</summary>
		[Description("是否删除")]
        public bool? Isdelete { get; set; } // Isdelete
        // Foreign keys

        /// <summary>
        /// Parent SysTitle pointed by [SysHandleLog].([SysTitleId]) (FK_SysHandleLog_SYSTITLE__SysTitle)
        /// </summary>
        public virtual SysTitle SysTitle { get; set; } // FK_SysHandleLog_SYSTITLE__SysTitle

        public SysHandleLog()
        {
            Isdelete = false;
        }
    }

    // SysPost
    ///<summary>
    /// 岗位
    ///</summary>
    [Table("SysPost")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public class SysPost : IAggregateRoot
    {

        ///<summary>
        /// 岗位主键Id
        ///</summary>
		[Description("岗位主键Id")]
        public System.Guid SysPostId { get; set; } // SysPostId (Primary key)

        ///<summary>
        /// 部门主键Id
        ///</summary>
		[Description("部门主键Id")]
        public System.Guid? SysDeptId { get; set; } // SysDeptId

        ///<summary>
        /// 岗位名称
        ///</summary>
		[Description("岗位名称")]
        public string PostName { get; set; } // PostName (length: 20)

        ///<summary>
        /// 岗位编号
        ///</summary>
		[Description("岗位编号")]
        public string PostCode { get; set; } // PostCode (length: 20)

        ///<summary>
        /// 岗位状态
        ///</summary>
		[Description("岗位状态")]
        public int? PostStatus { get; set; } // PostStatus

        ///<summary>
        /// 岗位说明
        ///</summary>
		[Description("岗位说明")]
        public string PostDesc { get; set; } // PostDesc (length: 200)

        ///<summary>
        /// 岗位所属机构Id
        ///</summary>
		[Description("岗位所属机构Id")]
        public System.Guid? PostCid { get; set; } // PostCid

        ///<summary>
        /// 是否删除
        ///</summary>
		[Description("是否删除")]
        public bool? Isdelete { get; set; } // Isdelete

        // Reverse navigation

        /// <summary>
        /// Child SysEmployees where [SysEmployee].[SysPostId] point to this entity (FK_SysEmployee_SYSEMPLOY_SysPost)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SysEmployee> SysEmployees { get; set; } // SysEmployee.FK_SysEmployee_SYSEMPLOY_SysPost
        // Foreign keys

        /// <summary>
        /// Parent SysDept pointed by [SysPost].([SysDeptId]) (FK_SysPost_SYSDEPT_S_SysDept)
        /// </summary>
        public virtual SysDept SysDept { get; set; } // FK_SysPost_SYSDEPT_S_SysDept

        public SysPost()
        {
            SysEmployees = new System.Collections.Generic.List<SysEmployee>();
        }
    }

    // SysQuartzTask
    ///<summary>
    /// 全区调度任务
    ///</summary>
    [Table("SysQuartzTask")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public class SysQuartzTask : IAggregateRoot
    {

        ///<summary>
        /// 任务Id
        ///</summary>
		[Description("任务Id")]
        public System.Guid QuartzTaskId { get; set; } // QuartzTaskId (Primary key)

        ///<summary>
        /// 机构Id
        ///</summary>
		[Description("机构Id")]
        public System.Guid? SysCompanyId { get; set; } // SysCompanyId

        ///<summary>
        /// 任务名称
        ///</summary>
		[Description("任务名称")]
        public string QuartzTaskName { get; set; } // QuartzTaskName (length: 50)

        ///<summary>
        /// 任务类型（0：系统服务 1：定时任务 2：接入服务）
        ///</summary>
		[Description("任务类型（0：系统服务 1：定时任务 2：接入服务）")]
        public int? QuartzTaskType { get; set; } // QuartzTaskType

        ///<summary>
        /// 接口参数
        ///</summary>
		[Description("接口参数")]
        public string QuartzTaskParams { get; set; } // QuartzTaskParams

        ///<summary>
        /// 任务状态（0：停止 1：启动）
        ///</summary>
		[Description("任务状态（0：停止 1：启动）")]
        public int? QuartzTaskStatus { get; set; } // QuartzTaskStatus

        ///<summary>
        /// 任务最近运行时间
        ///</summary>
		[Description("任务最近运行时间")]
        public System.DateTime? RecentRunTime { get; set; } // RecentRunTime

        ///<summary>
        /// 任务下次运行时间
        ///</summary>
		[Description("任务下次运行时间")]
        public System.DateTime? NextFireTime { get; set; } // NextFireTime

        ///<summary>
        /// 任务执行频率Cron
        ///</summary>
		[Description("任务执行频率Cron")]
        public string CronExpressionString { get; set; } // CronExpressionString (length: 500)

        ///<summary>
        /// 修改状态
        ///</summary>
		[Description("修改状态")]
        public int? IsModify { get; set; } // IsModify

        ///<summary>
        /// 任务程序集部件名称
        ///</summary>
		[Description("任务程序集部件名称")]
        public string PartName { get; set; } // PartName (length: 500)

        ///<summary>
        /// 任务程序集类名
        ///</summary>
		[Description("任务程序集类名")]
        public string ClassName { get; set; } // ClassName (length: 500)

        ///<summary>
        /// 任务开始时间
        ///</summary>
		[Description("任务开始时间")]
        public System.DateTime? StartTime { get; set; } // StartTime

        ///<summary>
        /// 任务结束时间
        ///</summary>
		[Description("任务结束时间")]
        public System.DateTime? EndTime { get; set; } // EndTime

        ///<summary>
        /// 重试次数
        ///</summary>
		[Description("重试次数")]
        public int? RetryCount { get; set; } // RetryCount

        ///<summary>
        /// 接口请求类型
        ///</summary>
		[Description("接口请求类型")]
        public int? RequestType { get; set; } // RequestType

        ///<summary>
        /// 接口超时时间
        ///</summary>
		[Description("接口超时时间")]
        public int? TimeOut { get; set; } // TimeOut

        ///<summary>
        /// 接口Url
        ///</summary>
		[Description("接口Url")]
        public string QuartzTaskUrl { get; set; } // QuartzTaskUrl (length: 8000)

        ///<summary>
        /// 备注
        ///</summary>
		[Description("备注")]
        public string QuartzTaskDesc { get; set; } // QuartzTaskDesc (length: 500)

        ///<summary>
        /// 是否删除
        ///</summary>
		[Description("是否删除")]
        public bool? Isdelete { get; set; } // Isdelete

        // Reverse navigation

        /// <summary>
        /// Child SysQuartzTaskLogs where [SysQuartzTaskLog].[QuartzTaskId] point to this entity (FK_SysQuartzTaskLog_SYSQUARTZ_SysQuartzTask)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SysQuartzTaskLog> SysQuartzTaskLogs { get; set; } // SysQuartzTaskLog.FK_SysQuartzTaskLog_SYSQUARTZ_SysQuartzTask
        // Foreign keys

        /// <summary>
        /// Parent SysCompany pointed by [SysQuartzTask].([SysCompanyId]) (FK_SysQuartzTask_SYSCOMPAN_SysCompany)
        /// </summary>
        public virtual SysCompany SysCompany { get; set; } // FK_SysQuartzTask_SYSCOMPAN_SysCompany

        public SysQuartzTask()
        {
            SysQuartzTaskLogs = new System.Collections.Generic.List<SysQuartzTaskLog>();
        }
    }

    // SysQuartzTaskLog
    ///<summary>
    /// 调度任务执行日志
    ///</summary>
    [Table("SysQuartzTaskLog")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public class SysQuartzTaskLog : IAggregateRoot
    {

        ///<summary>
        /// 任务执行日志Id
        ///</summary>
		[Description("任务执行日志Id")]
        public System.Guid SysQuartzTaskLogId { get; set; } // SysQuartzTaskLogId (Primary key)

        ///<summary>
        /// 任务Id
        ///</summary>
		[Description("任务Id")]
        public System.Guid? QuartzTaskId { get; set; } // QuartzTaskId

        ///<summary>
        /// 任务开始时间
        ///</summary>
		[Description("任务开始时间")]
        public System.DateTime? StartTime { get; set; } // StartTime

        ///<summary>
        /// 任务结束时间
        ///</summary>
		[Description("任务结束时间")]
        public System.DateTime? EndTime { get; set; } // EndTime

        ///<summary>
        /// 执行结果
        ///</summary>
		[Description("执行结果")]
        public string ExecuteResult { get; set; } // ExecuteResult

        ///<summary>
        /// 是否成功
        ///</summary>
		[Description("是否成功")]
        public bool? IsSuccess { get; set; } // IsSuccess

        ///<summary>
        /// 第几次执行
        ///</summary>
		[Description("第几次执行")]
        public int? ExecuteCount { get; set; } // ExecuteCount

        ///<summary>
        /// 遗留问题
        ///</summary>
		[Description("遗留问题")]
        public string LeftQuestionResult { get; set; } // LeftQuestionResult

        ///<summary>
        /// 执行类型（0：手动 1：自动）
        ///</summary>
		[Description("执行类型（0：手动 1：自动）")]
        public int? ExecutionType { get; set; } // ExecutionType

        ///<summary>
        /// 任务日志所属机构
        ///</summary>
		[Description("任务日志所属机构")]
        public System.Guid? SysQuartzTaskLogCid { get; set; } // SysQuartzTaskLogCid
        // Foreign keys

        /// <summary>
        /// Parent SysQuartzTask pointed by [SysQuartzTaskLog].([QuartzTaskId]) (FK_SysQuartzTaskLog_SYSQUARTZ_SysQuartzTask)
        /// </summary>
        public virtual SysQuartzTask SysQuartzTask { get; set; } // FK_SysQuartzTaskLog_SYSQUARTZ_SysQuartzTask
    }

    // SysTitle
    ///<summary>
    /// 系统模块
    ///</summary>
    [Table("SysTitle")]
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public class SysTitle : IAggregateRoot
    {

        ///<summary>
        /// 系统模块主键Id
        ///</summary>
		[Description("系统模块主键Id")]
        public System.Guid SysTitleId { get; set; } // SysTitleId (Primary key)

        ///<summary>
        /// 模块名称
        ///</summary>
		[Description("模块名称")]
        public string TitleName { get; set; } // TitleName (length: 40)

        ///<summary>
        /// 模块地址
        ///</summary>
		[Description("模块地址")]
        public string TitleUrl { get; set; } // TitleUrl (length: 200)

        ///<summary>
        /// 是否显示
        ///</summary>
		[Description("是否显示")]
        public int? IsDisplay { get; set; } // IsDisplay

        ///<summary>
        /// 排序
        ///</summary>
		[Description("排序")]
        public int? TitleOrderIndex { get; set; } // TitleOrderIndex

        ///<summary>
        /// 父Id
        ///</summary>
		[Description("父Id")]
        public System.Guid? TitleFatherId { get; set; } // TitleFatherId

        ///<summary>
        /// 模块图标地址
        ///</summary>
		[Description("模块图标地址")]
        public string TitleImgUrl { get; set; } // TitleImgUrl (length: 200)

        ///<summary>
        /// 是否删除
        ///</summary>
		[Description("是否删除")]
        public bool? Isdelete { get; set; } // Isdelete

        ///<summary>
        /// 备注
        ///</summary>
		[Description("备注")]
        public string TitleDesc { get; set; } // TitleDesc (length: 500)

        // Reverse navigation

        /// <summary>
        /// Child SysHandleLogs where [SysHandleLog].[SysTitleId] point to this entity (FK_SysHandleLog_SYSTITLE__SysTitle)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<SysHandleLog> SysHandleLogs { get; set; } // SysHandleLog.FK_SysHandleLog_SYSTITLE__SysTitle

        public SysTitle()
        {
            Isdelete = false;
            SysHandleLogs = new System.Collections.Generic.List<SysHandleLog>();
        }
    }

	#endregion

	#region POCO Configuration

    // SysCompany
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public class SysCompanyConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SysCompany>
    {
        public SysCompanyConfiguration()
            : this("dbo")
        {
        }

        public SysCompanyConfiguration(string schema)
        {
			//ToTable("SysCompany", schema);
			            HasKey(x => x.SysCompanyId);

            Property(x => x.SysCompanyId).HasColumnName(@"SysCompanyId").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.SysCompanyName).HasColumnName(@"SysCompanyName").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.SysCompanyFatherId).HasColumnName(@"SysCompanyFatherId").HasColumnType("uniqueidentifier").IsOptional();
            Property(x => x.CompanyType).HasColumnName(@"CompanyType").HasColumnType("int").IsOptional();
            Property(x => x.CompanyStatus).HasColumnName(@"CompanyStatus").HasColumnType("int").IsOptional();
            Property(x => x.CompanyCode).HasColumnName(@"CompanyCode").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.CompanyPicPerson).HasColumnName(@"CompanyPicPerson").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(20);
            Property(x => x.CompanyEmail).HasColumnName(@"CompanyEmail").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.CompanyAddress).HasColumnName(@"CompanyAddress").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(200);
            Property(x => x.CompanyLogoName).HasColumnName(@"CompanyLogoName").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(100);
            Property(x => x.ReserveDecimalPoint).HasColumnName(@"ReserveDecimalPoint").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(20);
            Property(x => x.CompanyModel).HasColumnName(@"CompanyModel").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(200);
            Property(x => x.CompanyOrderIndex).HasColumnName(@"CompanyOrderIndex").HasColumnType("int").IsOptional();
            Property(x => x.CompanyHomeType).HasColumnName(@"CompanyHomeType").HasColumnType("int").IsOptional();
            Property(x => x.CompanyTopImgUrl).HasColumnName(@"CompanyTopImgUrl").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(200);
            Property(x => x.CompanyLogoImgUrl).HasColumnName(@"CompanyLogoImgUrl").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(200);
            Property(x => x.Version).HasColumnName(@"Version").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(40);
            Property(x => x.PrintImg).HasColumnName(@"PrintImg").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(200);
            Property(x => x.CreateTime).HasColumnName(@"CreateTime").HasColumnType("datetime").IsOptional();
            Property(x => x.CompanyDesc).HasColumnName(@"CompanyDesc").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(500);
            Property(x => x.Isdelete).HasColumnName(@"Isdelete").HasColumnType("bit").IsOptional();
            Property(x => x.CompanyLoginCode).HasColumnName(@"CompanyLoginCode").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(20);
            Property(x => x.CompanyTitle).HasColumnName(@"CompanyTitle").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
        }
    }

    // SysDataBackM
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public class SysDataBackMConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SysDataBackM>
    {
        public SysDataBackMConfiguration()
            : this("dbo")
        {
        }

        public SysDataBackMConfiguration(string schema)
        {
			//ToTable("SysDataBackM", schema);
			            HasKey(x => x.DataBackMId);

            Property(x => x.DataBackMId).HasColumnName(@"DataBackMId").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.SysEmployeeId).HasColumnName(@"SysEmployeeId").HasColumnType("uniqueidentifier").IsOptional();
            Property(x => x.DataBackMFileName).HasColumnName(@"DataBackMFileName").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(100);
            Property(x => x.DataBackMStartTime).HasColumnName(@"DataBackMStartTime").HasColumnType("datetime").IsOptional();
            Property(x => x.DataBackMEndTime).HasColumnName(@"DataBackMEndTime").HasColumnType("datetime").IsOptional();
            Property(x => x.DataBackMFileSize).HasColumnName(@"DataBackMFileSize").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(40);
            Property(x => x.DataBackMFilePath).HasColumnName(@"DataBackMFilePath").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(500);
        }
    }

    // SysDept
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public class SysDeptConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SysDept>
    {
        public SysDeptConfiguration()
            : this("dbo")
        {
        }

        public SysDeptConfiguration(string schema)
        {
			//ToTable("SysDept", schema);
			            HasKey(x => x.SysDeptId);

            Property(x => x.SysDeptId).HasColumnName(@"SysDeptId").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.SysCompanyId).HasColumnName(@"SysCompanyId").HasColumnType("uniqueidentifier").IsOptional();
            Property(x => x.DeptName).HasColumnName(@"DeptName").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(20);
            Property(x => x.DeptCode).HasColumnName(@"DeptCode").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(20);
            Property(x => x.DeptType).HasColumnName(@"DeptType").HasColumnType("int").IsOptional();
            Property(x => x.DeptStatus).HasColumnName(@"DeptStatus").HasColumnType("int").IsOptional();
            Property(x => x.DeptDesc).HasColumnName(@"DeptDesc").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(200);
            Property(x => x.DeptFatherId).HasColumnName(@"DeptFatherId").HasColumnType("uniqueidentifier").IsOptional();
            Property(x => x.Isdelete).HasColumnName(@"Isdelete").HasColumnType("bit").IsOptional();

            // Foreign keys
            HasOptional(a => a.SysCompany).WithMany(b => b.SysDepts).HasForeignKey(c => c.SysCompanyId).WillCascadeOnDelete(false); // FK_SysDept_SYSCOMPAN_SysCompany
        }
    }

    // SysEmployee
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public class SysEmployeeConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SysEmployee>
    {
        public SysEmployeeConfiguration()
            : this("dbo")
        {
        }

        public SysEmployeeConfiguration(string schema)
        {
			//ToTable("SysEmployee", schema);
			            HasKey(x => x.SysEmployeeId);

            Property(x => x.SysEmployeeId).HasColumnName(@"SysEmployeeId").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.SysCompanyId).HasColumnName(@"SysCompanyId").HasColumnType("uniqueidentifier").IsOptional();
            Property(x => x.SysPostId).HasColumnName(@"SysPostId").HasColumnType("uniqueidentifier").IsOptional();
            Property(x => x.EmployeeName).HasColumnName(@"EmployeeName").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(30);
            Property(x => x.EmployeeCode).HasColumnName(@"EmployeeCode").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(20);
            Property(x => x.EmployeeType).HasColumnName(@"EmployeeType").HasColumnType("int").IsOptional();
            Property(x => x.EmployeeStatus).HasColumnName(@"EmployeeStatus").HasColumnType("int").IsOptional();
            Property(x => x.Sex).HasColumnName(@"Sex").HasColumnType("int").IsOptional();
            Property(x => x.Birthday).HasColumnName(@"Birthday").HasColumnType("datetime").IsOptional();
            Property(x => x.Telphone).HasColumnName(@"Telphone").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(22);
            Property(x => x.NumberLoseTime).HasColumnName(@"NumberLoseTime").HasColumnType("datetime").IsOptional();
            Property(x => x.IdNumber).HasColumnName(@"IdNumber").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(100);
            Property(x => x.EmployeeId).HasColumnName(@"EmployeeId").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(40);
            Property(x => x.EmployeePwd).HasColumnName(@"EmployeePwd").HasColumnType("varchar").IsRequired().IsUnicode(false).HasMaxLength(40);
            Property(x => x.EmployeePhotoUrl).HasColumnName(@"EmployeePhotoUrl").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(200);

            // Foreign keys
            HasOptional(a => a.SysCompany).WithMany(b => b.SysEmployees).HasForeignKey(c => c.SysCompanyId).WillCascadeOnDelete(false); // FK_SysEmployee_SYSEMPLOY_SysCompany
            HasOptional(a => a.SysPost).WithMany(b => b.SysEmployees).HasForeignKey(c => c.SysPostId).WillCascadeOnDelete(false); // FK_SysEmployee_SYSEMPLOY_SysPost
        }
    }

    // SysHandleLog
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public class SysHandleLogConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SysHandleLog>
    {
        public SysHandleLogConfiguration()
            : this("dbo")
        {
        }

        public SysHandleLogConfiguration(string schema)
        {
			//ToTable("SysHandleLog", schema);
			            HasKey(x => x.SysHandleLogId);

            Property(x => x.SysHandleLogId).HasColumnName(@"SysHandleLogId").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.SysEmployeeId).HasColumnName(@"SysEmployeeId").HasColumnType("uniqueidentifier").IsOptional();
            Property(x => x.SysTitleId).HasColumnName(@"SysTitleId").HasColumnType("uniqueidentifier").IsOptional();
            Property(x => x.HandleTime).HasColumnName(@"HandleTime").HasColumnType("datetime").IsOptional();
            Property(x => x.HandleAction).HasColumnName(@"HandleAction").HasColumnType("int").IsOptional();
            Property(x => x.HandleDataId).HasColumnName(@"HandleDataId").HasColumnType("uniqueidentifier").IsOptional();
            Property(x => x.HandleLogIP).HasColumnName(@"HandleLogIP").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(100);
            Property(x => x.HandleActionCID).HasColumnName(@"HandleActionCID").HasColumnType("uniqueidentifier").IsOptional();
            Property(x => x.HandleLogDesc).HasColumnName(@"HandleLogDesc").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(500);
            Property(x => x.Isdelete).HasColumnName(@"Isdelete").HasColumnType("bit").IsOptional();

            // Foreign keys
            HasOptional(a => a.SysTitle).WithMany(b => b.SysHandleLogs).HasForeignKey(c => c.SysTitleId).WillCascadeOnDelete(false); // FK_SysHandleLog_SYSTITLE__SysTitle
        }
    }

    // SysPost
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public class SysPostConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SysPost>
    {
        public SysPostConfiguration()
            : this("dbo")
        {
        }

        public SysPostConfiguration(string schema)
        {
			//ToTable("SysPost", schema);
			            HasKey(x => x.SysPostId);

            Property(x => x.SysPostId).HasColumnName(@"SysPostId").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.SysDeptId).HasColumnName(@"SysDeptId").HasColumnType("uniqueidentifier").IsOptional();
            Property(x => x.PostName).HasColumnName(@"PostName").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(20);
            Property(x => x.PostCode).HasColumnName(@"PostCode").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(20);
            Property(x => x.PostStatus).HasColumnName(@"PostStatus").HasColumnType("int").IsOptional();
            Property(x => x.PostDesc).HasColumnName(@"PostDesc").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(200);
            Property(x => x.PostCid).HasColumnName(@"PostCid").HasColumnType("uniqueidentifier").IsOptional();
            Property(x => x.Isdelete).HasColumnName(@"Isdelete").HasColumnType("bit").IsOptional();

            // Foreign keys
            HasOptional(a => a.SysDept).WithMany(b => b.SysPosts).HasForeignKey(c => c.SysDeptId).WillCascadeOnDelete(false); // FK_SysPost_SYSDEPT_S_SysDept
        }
    }

    // SysQuartzTask
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public class SysQuartzTaskConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SysQuartzTask>
    {
        public SysQuartzTaskConfiguration()
            : this("dbo")
        {
        }

        public SysQuartzTaskConfiguration(string schema)
        {
			//ToTable("SysQuartzTask", schema);
			            HasKey(x => x.QuartzTaskId);

            Property(x => x.QuartzTaskId).HasColumnName(@"QuartzTaskId").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.SysCompanyId).HasColumnName(@"SysCompanyId").HasColumnType("uniqueidentifier").IsOptional();
            Property(x => x.QuartzTaskName).HasColumnName(@"QuartzTaskName").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(50);
            Property(x => x.QuartzTaskType).HasColumnName(@"QuartzTaskType").HasColumnType("int").IsOptional();
            Property(x => x.QuartzTaskParams).HasColumnName(@"QuartzTaskParams").HasColumnType("xml").IsOptional();
            Property(x => x.QuartzTaskStatus).HasColumnName(@"QuartzTaskStatus").HasColumnType("int").IsOptional();
            Property(x => x.RecentRunTime).HasColumnName(@"RecentRunTime").HasColumnType("datetime").IsOptional();
            Property(x => x.NextFireTime).HasColumnName(@"NextFireTime").HasColumnType("datetime").IsOptional();
            Property(x => x.CronExpressionString).HasColumnName(@"CronExpressionString").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(500);
            Property(x => x.IsModify).HasColumnName(@"IsModify").HasColumnType("int").IsOptional();
            Property(x => x.PartName).HasColumnName(@"PartName").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(500);
            Property(x => x.ClassName).HasColumnName(@"ClassName").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(500);
            Property(x => x.StartTime).HasColumnName(@"StartTime").HasColumnType("datetime").IsOptional();
            Property(x => x.EndTime).HasColumnName(@"EndTime").HasColumnType("datetime").IsOptional();
            Property(x => x.RetryCount).HasColumnName(@"RetryCount").HasColumnType("int").IsOptional();
            Property(x => x.RequestType).HasColumnName(@"RequestType").HasColumnType("int").IsOptional();
            Property(x => x.TimeOut).HasColumnName(@"TimeOut").HasColumnType("int").IsOptional();
            Property(x => x.QuartzTaskUrl).HasColumnName(@"QuartzTaskUrl").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(8000);
            Property(x => x.QuartzTaskDesc).HasColumnName(@"QuartzTaskDesc").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(500);
            Property(x => x.Isdelete).HasColumnName(@"Isdelete").HasColumnType("bit").IsOptional();

            // Foreign keys
            HasOptional(a => a.SysCompany).WithMany(b => b.SysQuartzTasks).HasForeignKey(c => c.SysCompanyId).WillCascadeOnDelete(false); // FK_SysQuartzTask_SYSCOMPAN_SysCompany
        }
    }

    // SysQuartzTaskLog
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public class SysQuartzTaskLogConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SysQuartzTaskLog>
    {
        public SysQuartzTaskLogConfiguration()
            : this("dbo")
        {
        }

        public SysQuartzTaskLogConfiguration(string schema)
        {
			//ToTable("SysQuartzTaskLog", schema);
			            HasKey(x => x.SysQuartzTaskLogId);

            Property(x => x.SysQuartzTaskLogId).HasColumnName(@"SysQuartzTaskLogId").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.QuartzTaskId).HasColumnName(@"QuartzTaskId").HasColumnType("uniqueidentifier").IsOptional();
            Property(x => x.StartTime).HasColumnName(@"StartTime").HasColumnType("datetime").IsOptional();
            Property(x => x.EndTime).HasColumnName(@"EndTime").HasColumnType("datetime").IsOptional();
            Property(x => x.ExecuteResult).HasColumnName(@"ExecuteResult").HasColumnType("xml").IsOptional();
            Property(x => x.IsSuccess).HasColumnName(@"IsSuccess").HasColumnType("bit").IsOptional();
            Property(x => x.ExecuteCount).HasColumnName(@"ExecuteCount").HasColumnType("int").IsOptional();
            Property(x => x.LeftQuestionResult).HasColumnName(@"LeftQuestionResult").HasColumnType("xml").IsOptional();
            Property(x => x.ExecutionType).HasColumnName(@"ExecutionType").HasColumnType("int").IsOptional();
            Property(x => x.SysQuartzTaskLogCid).HasColumnName(@"SysQuartzTaskLogCid").HasColumnType("uniqueidentifier").IsOptional();

            // Foreign keys
            HasOptional(a => a.SysQuartzTask).WithMany(b => b.SysQuartzTaskLogs).HasForeignKey(c => c.QuartzTaskId).WillCascadeOnDelete(false); // FK_SysQuartzTaskLog_SYSQUARTZ_SysQuartzTask
        }
    }

    // SysTitle
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public class SysTitleConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<SysTitle>
    {
        public SysTitleConfiguration()
            : this("dbo")
        {
        }

        public SysTitleConfiguration(string schema)
        {
			//ToTable("SysTitle", schema);
			            HasKey(x => x.SysTitleId);

            Property(x => x.SysTitleId).HasColumnName(@"SysTitleId").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.TitleName).HasColumnName(@"TitleName").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(40);
            Property(x => x.TitleUrl).HasColumnName(@"TitleUrl").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(200);
            Property(x => x.IsDisplay).HasColumnName(@"IsDisplay").HasColumnType("int").IsOptional();
            Property(x => x.TitleOrderIndex).HasColumnName(@"TitleOrderIndex").HasColumnType("int").IsOptional();
            Property(x => x.TitleFatherId).HasColumnName(@"TitleFatherId").HasColumnType("uniqueidentifier").IsOptional();
            Property(x => x.TitleImgUrl).HasColumnName(@"TitleImgUrl").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(200);
            Property(x => x.Isdelete).HasColumnName(@"Isdelete").HasColumnType("bit").IsOptional();
            Property(x => x.TitleDesc).HasColumnName(@"TitleDesc").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(500);
        }
    }

	#endregion

	#region Stored procedure return models


    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public class proc_BackupReturnModel
    {
        public System.String CodeChar { get; set; }
    }


    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.30.0.0")]
    public class proc_RestoreDbReturnModel
    {
        public System.String CodeChar { get; set; }
    }

	#endregion

}
// </auto-generated>
