 
/************************************************************************
 * FileName  DataTable\DataTableContextInfrastructure.IAg
 * FileDesc data/context
 * Author   System
 * CreateTime 2018-08-29 17:44:04

 * Copyright (c) Titan.Han  2017. All Rights Reserved. 
 * ***********************************************************************/

// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning
namespace Titan.Model.DataModel
{
    using System;
    using System.Linq;
    using Titan.Model;
    using System.Data.Entity;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations.Schema;


    public partial class ModelBaseContext : DbContext
    {
	    public ModelBaseContext()
		: base("name=ModelBaseContext")
        {}

        public virtual DbSet<SysCompany> SysCompany { get; set; } // SysCompany
        public virtual DbSet<SysDataBackM> SysDataBackM { get; set; } // SysDataBackM
        public virtual DbSet<SysDept> SysDept { get; set; } // SysDept
        public virtual DbSet<SysEmployee> SysEmployee { get; set; } // SysEmployee
        public virtual DbSet<SysHandleLog> SysHandleLog { get; set; } // SysHandleLog
        public virtual DbSet<SysPost> SysPost { get; set; } // SysPost
        public virtual DbSet<SysQuartzTask> SysQuartzTask { get; set; } // SysQuartzTask
        public virtual DbSet<SysQuartzTaskLog> SysQuartzTaskLog { get; set; } // SysQuartzTaskLog
        public virtual DbSet<SysTitle> SysTitle { get; set; } // SysTitle

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Configurations.Add(new SysCompanyConfiguration());
            modelBuilder.Configurations.Add(new SysDataBackMConfiguration());
            modelBuilder.Configurations.Add(new SysDeptConfiguration());
            modelBuilder.Configurations.Add(new SysEmployeeConfiguration());
            modelBuilder.Configurations.Add(new SysHandleLogConfiguration());
            modelBuilder.Configurations.Add(new SysPostConfiguration());
            modelBuilder.Configurations.Add(new SysQuartzTaskConfiguration());
            modelBuilder.Configurations.Add(new SysQuartzTaskLogConfiguration());
            modelBuilder.Configurations.Add(new SysTitleConfiguration());
        }
    }
}
// </auto-generated>
